export const COMMON_TYPES = [
  "bigint",
  "bigint generated always as identity",
  "boolean",
  "bytea",
  "date",
  "double precision",
  "integer",
  "interval",
  "json",
  "jsonb",
  "numeric",
  "numeric(12,2)",
  "real",
  "serial",
  "smallint",
  "text",
  "text[]",
  "time",
  "timestamp",
  "timestamptz",
  "uuid",
  "varchar(255)",
  "vector(1536)",
] as const;
